apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  labels:
    app: kiali
    version: v0.7.2
data:
  config.yaml: |
    server:
      port: 20001
      static_content_root_directory: /opt/kiali/console
    external_services:
      jaeger:
        url: http://jaeger-query-istio-system.127.0.0.1.nip.io
      grafana:
        url: http://grafana-istio-system.127.0.0.1.nip.io
